//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public double Evaluation { get; set; }
        public int TreatmentId { get; set; }
        public string AspNetUserId { get; set; }
    
        public virtual Treatment Treatment { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
