//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Treatment
    {
       
        public Treatment()
        {
            this.Appointments = new HashSet<Appointment>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "Please enter a name.")]
        [RegularExpression("[a-zA-Z0-9 ]+$", ErrorMessage = "input can be letter and space only")]
        [StringLength(30, MinimumLength = 2, ErrorMessage = "Name length not be allowed.")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please enter a Location.")]
        [RegularExpression("[a-zA-Z0-9 ]+$", ErrorMessage = "input can be letter and space only")]
        public string Location { get; set; }
        public Nullable<double> Rating { get; set; }
        [Required(ErrorMessage = "Please enter a phone number.")]
        [Range(0111111111,9999999999, ErrorMessage = "Please input the correct phone number.")]
        public int Phone { get; set; }
    
  
        public virtual ICollection<Appointment> Appointments { get; set; }
    }
}
